version: "3.9"
services:
    db:
       container_name: mysqldocdb
       image: mysql:5.7
       command: mysqld
       ports:
        - "3306:3306"
       volumes:
        - data:/var/lib/mysql
        - ./dboutput:/var/lib/mysql-files
       environment: 
        - MYSQL_ROOT_PASSWORD=MyDogHas1Flea
        - MYSQL_DATABASE=mysqldoc
        - MYSQL_USER=mrankin
        - MYSQL_PASSWORD=1Chainmail
        - MYSQL_ROOT_HOST=%
volumes:
    data: